development:
  secret_key_base: abfa524bf956f7905d5e23bd2d8304521334294676d67c1abbd4cdf5032208cac4e1d13a8e117e4d3b848b7828297e496c9513cc511e5c705112635e0832c9be

test:
  secret_key_base: f20562fa97d018add54ce7784c49a6c48ae1131525696b1a9b00bc200be81c5448d27e32060b54c2f364f52dfe57344e4f03d560781f596e12257a059a7b8ec2

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
